require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FormalitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Formality. As you add validations to Formality, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormalitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all formalities as @formalities" do
      formality = Formality.create! valid_attributes
      get :index, {}, valid_session
      assigns(:formalities).should eq([formality])
    end
  end

  describe "GET show" do
    it "assigns the requested formality as @formality" do
      formality = Formality.create! valid_attributes
      get :show, {:id => formality.to_param}, valid_session
      assigns(:formality).should eq(formality)
    end
  end

  describe "GET new" do
    it "assigns a new formality as @formality" do
      get :new, {}, valid_session
      assigns(:formality).should be_a_new(Formality)
    end
  end

  describe "GET edit" do
    it "assigns the requested formality as @formality" do
      formality = Formality.create! valid_attributes
      get :edit, {:id => formality.to_param}, valid_session
      assigns(:formality).should eq(formality)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Formality" do
        expect {
          post :create, {:formality => valid_attributes}, valid_session
        }.to change(Formality, :count).by(1)
      end

      it "assigns a newly created formality as @formality" do
        post :create, {:formality => valid_attributes}, valid_session
        assigns(:formality).should be_a(Formality)
        assigns(:formality).should be_persisted
      end

      it "redirects to the created formality" do
        post :create, {:formality => valid_attributes}, valid_session
        response.should redirect_to(Formality.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved formality as @formality" do
        # Trigger the behavior that occurs when invalid params are submitted
        Formality.any_instance.stub(:save).and_return(false)
        post :create, {:formality => { "name" => "invalid value" }}, valid_session
        assigns(:formality).should be_a_new(Formality)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Formality.any_instance.stub(:save).and_return(false)
        post :create, {:formality => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested formality" do
        formality = Formality.create! valid_attributes
        # Assuming there are no other formalities in the database, this
        # specifies that the Formality created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Formality.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => formality.to_param, :formality => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested formality as @formality" do
        formality = Formality.create! valid_attributes
        put :update, {:id => formality.to_param, :formality => valid_attributes}, valid_session
        assigns(:formality).should eq(formality)
      end

      it "redirects to the formality" do
        formality = Formality.create! valid_attributes
        put :update, {:id => formality.to_param, :formality => valid_attributes}, valid_session
        response.should redirect_to(formality)
      end
    end

    describe "with invalid params" do
      it "assigns the formality as @formality" do
        formality = Formality.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Formality.any_instance.stub(:save).and_return(false)
        put :update, {:id => formality.to_param, :formality => { "name" => "invalid value" }}, valid_session
        assigns(:formality).should eq(formality)
      end

      it "re-renders the 'edit' template" do
        formality = Formality.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Formality.any_instance.stub(:save).and_return(false)
        put :update, {:id => formality.to_param, :formality => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested formality" do
      formality = Formality.create! valid_attributes
      expect {
        delete :destroy, {:id => formality.to_param}, valid_session
      }.to change(Formality, :count).by(-1)
    end

    it "redirects to the formalities list" do
      formality = Formality.create! valid_attributes
      delete :destroy, {:id => formality.to_param}, valid_session
      response.should redirect_to(formalities_url)
    end
  end

end
