require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrearrivalsController do

  # This should return the minimal set of attributes required to create a valid
  # Prearrival. As you add validations to Prearrival, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrearrivalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prearrivals as @prearrivals" do
      prearrival = Prearrival.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prearrivals).should eq([prearrival])
    end
  end

  describe "GET show" do
    it "assigns the requested prearrival as @prearrival" do
      prearrival = Prearrival.create! valid_attributes
      get :show, {:id => prearrival.to_param}, valid_session
      assigns(:prearrival).should eq(prearrival)
    end
  end

  describe "GET new" do
    it "assigns a new prearrival as @prearrival" do
      get :new, {}, valid_session
      assigns(:prearrival).should be_a_new(Prearrival)
    end
  end

  describe "GET edit" do
    it "assigns the requested prearrival as @prearrival" do
      prearrival = Prearrival.create! valid_attributes
      get :edit, {:id => prearrival.to_param}, valid_session
      assigns(:prearrival).should eq(prearrival)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prearrival" do
        expect {
          post :create, {:prearrival => valid_attributes}, valid_session
        }.to change(Prearrival, :count).by(1)
      end

      it "assigns a newly created prearrival as @prearrival" do
        post :create, {:prearrival => valid_attributes}, valid_session
        assigns(:prearrival).should be_a(Prearrival)
        assigns(:prearrival).should be_persisted
      end

      it "redirects to the created prearrival" do
        post :create, {:prearrival => valid_attributes}, valid_session
        response.should redirect_to(Prearrival.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prearrival as @prearrival" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prearrival.any_instance.stub(:save).and_return(false)
        post :create, {:prearrival => { "title" => "invalid value" }}, valid_session
        assigns(:prearrival).should be_a_new(Prearrival)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prearrival.any_instance.stub(:save).and_return(false)
        post :create, {:prearrival => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prearrival" do
        prearrival = Prearrival.create! valid_attributes
        # Assuming there are no other prearrivals in the database, this
        # specifies that the Prearrival created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prearrival.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => prearrival.to_param, :prearrival => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested prearrival as @prearrival" do
        prearrival = Prearrival.create! valid_attributes
        put :update, {:id => prearrival.to_param, :prearrival => valid_attributes}, valid_session
        assigns(:prearrival).should eq(prearrival)
      end

      it "redirects to the prearrival" do
        prearrival = Prearrival.create! valid_attributes
        put :update, {:id => prearrival.to_param, :prearrival => valid_attributes}, valid_session
        response.should redirect_to(prearrival)
      end
    end

    describe "with invalid params" do
      it "assigns the prearrival as @prearrival" do
        prearrival = Prearrival.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prearrival.any_instance.stub(:save).and_return(false)
        put :update, {:id => prearrival.to_param, :prearrival => { "title" => "invalid value" }}, valid_session
        assigns(:prearrival).should eq(prearrival)
      end

      it "re-renders the 'edit' template" do
        prearrival = Prearrival.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prearrival.any_instance.stub(:save).and_return(false)
        put :update, {:id => prearrival.to_param, :prearrival => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prearrival" do
      prearrival = Prearrival.create! valid_attributes
      expect {
        delete :destroy, {:id => prearrival.to_param}, valid_session
      }.to change(Prearrival, :count).by(-1)
    end

    it "redirects to the prearrivals list" do
      prearrival = Prearrival.create! valid_attributes
      delete :destroy, {:id => prearrival.to_param}, valid_session
      response.should redirect_to(prearrivals_url)
    end
  end

end
